# Generated by Django 5.0.1 on 2024-01-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_add_slug-to-product'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.SmallIntegerField(null=True),
        ),
    ]
