# Generated by Django 5.0.1 on 2024-01-28 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_collection_product_collection_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='collection_id',
            new_name='collection',
        ),
    ]
